# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  PROJECT: fifth-sunup-329021    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.PROJECT}}
          service_account_key: ${{ secrets.GCP_SA }}
          export_default_credentials: true

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@v0.6.0
        with:
          name: helloPubSub
          runtime: nodejs14

      - name: make the url aunthenticated
        run: |
          gcloud iam service-accounts add-iam-policy-binding fifth-sunup-329021@appspot.gserviceaccount.com --member=serviceAccount:cloud-storage-func@fifth-sunup-329021.iam.gserviceaccount.com --role=roles/iam.serviceAccountUser
      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"

